sudo: false
language: cpp
compiler:
  - gcc
os:
  - linux

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-4.8
    - g++-4.8

# List in here all the subdirectories you need to test
# this format will create a matrix for all required tests.
env: 
  - TEST_DIR=CA1-1
  - TEST_DIR=CA1-2
  - TEST_DIR=CA1-3
  - TEST_DIR=CA1-4
  - TEST_DIR=CA1-5

#  
script:
  # cd into CA#
  - cd $TEST_DIR
  - mkdir build
  - cd build
  - cmake ..
  - make
  # Run unit test file
  - ./ca_test